import Head from 'next/head';

export default function Home() {
  return (
    <div className='container mx-10'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='mt-10 text-center'>
        <h1 className='text-blue-500'>Welcome to Mukk Blog</h1>
      </main>
    </div>
  );
}
